# config file
max_clients 100
types_path	./conf/types.conf

server {
	port 8080
	server_name localhost

	error_page /cookie.html 504

	location /cookie.html {
		root ./content
	}

	location /old.html {
		return 301 new.html
	}
	
	location / {
		root ./content
		index index.html
		autoindex YES
		allowed_methods GET POST
	}

	location /cgi/ { 
		root ./
		isCgi	YES
		cgi_assign {
			/usr/bin/python3 	.py
			/usr/bin/bash		.sh
			/usr/bin/php-cgi		.php
			/home/dafx/Downloads/cgi_tester .foo
		}
		allowed_methods GET POST DELETE
	}

	location /site/actions/ {
		root ./
		isCgi	YES
		cgi_assign {
			/usr/bin/php-cgi		.php
		}
		allowed_methods GET POST
	}

	location /site/ {
		root ./
		autoindex YES
		allowed_methods GET POST
	}

	location /uploads/ {
		root ./
		upload_dir ./uploads/
		isUploadable YES
		allowed_methods GET POST DELETE
	}
	
}

server {
	port 8081
	server_name localhost

	location / {
		root ./test
		autoindex YES
		allowed_methods GET POST
	}
}
